/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package components;

import java.sql.Connection;
import config.MysqlClient;
import java.io.File;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import javax.swing.JFrame;

/**
 *
 * @author lumiere
 */
public class FormBuku extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormBuku.class.getName());
    private DefaultTableModel table;
    MysqlClient mysqlClient = new MysqlClient();
    Connection connect = mysqlClient.createConnection();
    JasperReport JasReport;
    JasperPrint JasPrint;
    HashMap parameter = new HashMap();
    JasperDesign JasDesign;
    
    /**
     * Creates new form FormBuku
     */
    public FormBuku(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        String[] data={"Kode Buku","Judul Buku","Penerbit","Penulis","Jumlah Buku", "Lokasi Buku"};
        table = new DefaultTableModel(data,0);
        TabelBuku.setModel(table);
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        InputKodeBuku = new javax.swing.JTextField();
        InputJudulBuku = new javax.swing.JTextField();
        InputPenerbit = new javax.swing.JTextField();
        InputPenulis = new javax.swing.JTextField();
        InputJumlahBuku = new javax.swing.JTextField();
        InputLokasiBuku = new javax.swing.JTextField();
        ButtonSimpan = new javax.swing.JButton();
        ButtonEdit = new javax.swing.JButton();
        ButtonBatal = new javax.swing.JButton();
        ButtonHapus = new javax.swing.JButton();
        ButtonTutup = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelBuku = new javax.swing.JTable();
        ButtonCetak = new javax.swing.JButton();
        ButtonCari = new javax.swing.JButton();
        InputCari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Adwaita Sans", 1, 36)); // NOI18N
        jLabel1.setText("FORM BUKU");

        jLabel2.setText("Kode Buku:");

        jLabel3.setText("Judul Buku:");

        jLabel4.setText("Penerbit:");

        jLabel5.setText("Penulis");

        jLabel6.setText("Jumlah Buku:");

        jLabel7.setText("Lokasi Buku:");

        InputKodeBuku.addActionListener(this::InputKodeBukuActionPerformed);

        InputJudulBuku.addActionListener(this::InputJudulBukuActionPerformed);

        InputPenerbit.addActionListener(this::InputPenerbitActionPerformed);

        InputPenulis.addActionListener(this::InputPenulisActionPerformed);

        InputJumlahBuku.addActionListener(this::InputJumlahBukuActionPerformed);

        InputLokasiBuku.addActionListener(this::InputLokasiBukuActionPerformed);

        ButtonSimpan.setText("Simpan");
        ButtonSimpan.addActionListener(this::ButtonSimpanActionPerformed);

        ButtonEdit.setText("Edit");
        ButtonEdit.addActionListener(this::ButtonEditActionPerformed);

        ButtonBatal.setText("Batal");
        ButtonBatal.addActionListener(this::ButtonBatalActionPerformed);

        ButtonHapus.setText("Hapus");
        ButtonHapus.addActionListener(this::ButtonHapusActionPerformed);

        ButtonTutup.setText("Tutup");
        ButtonTutup.addActionListener(this::ButtonTutupActionPerformed);

        TabelBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelBuku);

        ButtonCetak.setText("Cetak");
        ButtonCetak.addActionListener(this::ButtonCetakActionPerformed);

        ButtonCari.setText("Cari");
        ButtonCari.addActionListener(this::ButtonCariActionPerformed);

        InputCari.addActionListener(this::InputCariActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ButtonSimpan)
                                    .addGap(28, 28, 28)
                                    .addComponent(ButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ButtonBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ButtonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ButtonTutup))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(InputLokasiBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(InputJumlahBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(InputPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(InputPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(InputJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(48, 48, 48)
                                    .addComponent(InputKodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(ButtonCari, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(InputCari)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ButtonCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(InputKodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(InputJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(InputPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(InputPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(InputJumlahBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(InputLokasiBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSimpan)
                    .addComponent(ButtonEdit)
                    .addComponent(ButtonBatal)
                    .addComponent(ButtonHapus)
                    .addComponent(ButtonTutup))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(InputCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonCari))
                    .addComponent(ButtonCetak))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputKodeBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputKodeBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputKodeBukuActionPerformed

    private void InputJudulBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputJudulBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputJudulBukuActionPerformed

    private void InputPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPenerbitActionPerformed

    private void InputPenulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPenulisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPenulisActionPerformed

    private void InputJumlahBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputJumlahBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputJumlahBukuActionPerformed

    private void InputLokasiBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputLokasiBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputLokasiBukuActionPerformed

    private void ButtonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCetakActionPerformed
        // TODO add your handling code here:
        try {
            File report = new File("./src/components/ReportBook.jrxml");
            JasperDesign JasDesign = JRXmlLoader.load(report);
            parameter.clear();
            JasReport = JasperCompileManager.compileReport(JasDesign);
            JasPrint = JasperFillManager.fillReport(JasReport, parameter, connect);
            // Buat instance JasperViewer
            JRViewer viewer = new JRViewer(JasPrint);

            // Buat JFrame baru sebagai container
            JFrame previewFrame = new JFrame("Preview Laporan");
            previewFrame.getContentPane().add(viewer);
            previewFrame.setExtendedState(JFrame.MAXIMIZED_BOTH); // full screen
            previewFrame.setAlwaysOnTop(true); // pastikan di atas
            previewFrame.setLocationRelativeTo(null); // tengah layar
            previewFrame.setVisible(true);
            previewFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }catch(Exception error) {
            JOptionPane.showMessageDialog(null,"Gagal print: " + error.getMessage());
            System.out.println("Gagal print: " + error.getMessage());
        }
    }//GEN-LAST:event_ButtonCetakActionPerformed

    private void ButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCariActionPerformed
        // TODO add your handling code here:
        String searchInput = InputCari.getText().trim();

        if (searchInput.equals("")) {
            JOptionPane.showMessageDialog(null, "Masukkan keyword terlebih dahulu!");
            InputCari.requestFocus();
            return;
        }

        try {
            int row = TabelBuku.getRowCount();
            for (int i = 0; i < row; i++) {
                table.removeRow(0);
            }

            // Query pencarian
            String query = "SELECT * FROM tabel_buku WHERE kode_buku LIKE ? OR judul_buku LIKE ?";
            PreparedStatement pst = connect.prepareStatement(query);
            pst.setString(1, "%" + searchInput + "%");
            pst.setString(2, "%" + searchInput + "%");

            ResultSet rs = pst.executeQuery();

            // Cek apakah data ditemukan
            boolean found = false;
            while (rs.next()) {
                found = true;
                String[] data = {
                    rs.getString("kode_buku"),
                    rs.getString("judul_buku"),
                    rs.getString("penerbit"),
                    rs.getString("penulis"),
                    rs.getString("jumlah_buku"),
                    rs.getString("lokasi_buku"),
                };
                table.addRow(data);
                System.out.println("hasil cari: " + Arrays.toString(data));
            }

            if (!found) {
                JOptionPane.showMessageDialog(rootPane,
                    "Kode Buku atau Judul Buku '" + searchInput + "' tidak ditemukan!\nSilahkan refresh untuk melihat tabel!");
                System.out.println("Kode Buku atau Judul Buku '" + searchInput + "' tidak ditemukan!\nSilahkan refresh untuk melihat tabel!");
            }
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(rootPane, "Database Error: " + error.getMessage());
            System.out.println("Database Error: " + error.getMessage());
        }
    }//GEN-LAST:event_ButtonCariActionPerformed

    private void InputCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputCariActionPerformed
        // TODO add your handling code here:
        ButtonCari.doClick();
    }//GEN-LAST:event_InputCariActionPerformed

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditActionPerformed
        // TODO add your handling code here:
        InputKodeBuku.setEnabled(true);
        if (InputKodeBuku.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Kode Buku tidak boleh kosong");
            InputKodeBuku.requestFocus();
        } else if (InputJudulBuku.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Judul Buku tidak boleh kosong");
            InputJudulBuku.requestFocus();
        } else if (InputPenerbit.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Penerbit tidak boleh kosong");
            InputPenerbit.requestFocus();
        } else if (InputPenulis.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Penulis tidak boleh kosong");
            InputPenulis.requestFocus();
        } else if (InputJumlahBuku.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Jumlah Buku tidak boleh kosong");
            InputJumlahBuku.requestFocus();
        } else if (InputLokasiBuku.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Lokasi Buku tidak boleh kosong");
            InputLokasiBuku.requestFocus();
        } else
            try {
                String kodeBarang  = InputKodeBuku.getText();
                String query = "UPDATE tabel_buku SET judul_buku = '" +InputJudulBuku.getText()+"',"
                        + " penerbit = '" +InputPenerbit.getText()+"', "
                        + " penulis = ' " +InputPenulis.getText()+"',  "
                        + " jumlah_buku = '" +InputJumlahBuku.getText()+"', "
                        + " lokasi_buku = '" +InputLokasiBuku.getText()+"' "
                        + "WHERE kode_buku = '" +kodeBarang+"'";
                int result = connect.createStatement().executeUpdate(query);
                JOptionPane.showMessageDialog(rootPane, "Data berhasil disimpan");
                InputKodeBuku.setText(null);
                InputJudulBuku.setText(null);
                InputPenerbit.setText(null);
                InputPenulis.setText(null);
                InputJumlahBuku.setText(null);
                InputLokasiBuku.setText(null);
//                InputKodeBarang.requestFocus();
                tampil(); //memanggil prosedur dengan nama tampil, prosedur harus dibuat terlebih dahulu
            } catch (SQLException error) {
                JOptionPane.showMessageDialog(rootPane, "Database Error: " + error.getMessage());
                System.out.println("Database Error: " + error.getMessage());
            }
    }//GEN-LAST:event_ButtonEditActionPerformed

    private void ButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBatalActionPerformed
        // TODO add your handling code here:
        InputKodeBuku.setEnabled(true);
        InputKodeBuku.setText(null);
        InputJudulBuku.setText(null);
        InputPenerbit.setText(null);
        InputPenulis.setText(null);
        InputJumlahBuku.setText(null);
        InputLokasiBuku.setText(null);
        InputCari.setText(null);
        InputKodeBuku.requestFocus();
        tampil();
    }//GEN-LAST:event_ButtonBatalActionPerformed

    private void ButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSimpanActionPerformed
        // TODO add your handling code here:
        InputKodeBuku.setEnabled(true);
         if (InputKodeBuku.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Kode Buku tidak boleh kosong");
            InputKodeBuku.requestFocus();
        } else if (InputJudulBuku.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Judul Buku tidak boleh kosong");
            InputJudulBuku.requestFocus();
        } else if (InputPenerbit.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Penerbit tidak boleh kosong");
            InputPenerbit.requestFocus();
        } else if (InputPenulis.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Penulis tidak boleh kosong");
            InputPenulis.requestFocus();
        } else if (InputJumlahBuku.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Jumlah Buku tidak boleh kosong");
            InputJumlahBuku.requestFocus();
        } else if (InputLokasiBuku.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Lokasi Buku tidak boleh kosong");
            InputLokasiBuku.requestFocus();
        } else
        try {
            String kodeBuku  = InputKodeBuku.getText();
            String cekQuery = "SELECT COUNT(*) FROM tabel_buku WHERE kode_buku = ?";
            PreparedStatement cekStmt = connect.prepareStatement(cekQuery);
            cekStmt.setString(1, InputKodeBuku.getText());
            ResultSet rs = cekStmt.executeQuery();

            rs.next();
            int jumlah = rs.getInt(1);

            if (jumlah > 0) {
                JOptionPane.showMessageDialog(rootPane,
                    "Kode Buku '" + kodeBuku + "' Sudah ada!\nSilakan gunakan kode lain.",
                    "Duplikasi Data",
                    JOptionPane.WARNING_MESSAGE);
                System.out.println("Kode Barang '" + kodeBuku + "' Sudah ada atau duplikasi ata");
                return;
            }

            connect.createStatement().executeUpdate("INSERT INTO tabel_buku VALUES('"
                    +InputKodeBuku.getText()+"','"
                    +InputJudulBuku.getText()+"','"
                    +InputPenerbit.getText()+"','"
                    +InputPenulis.getText()+"','"
                    +InputJumlahBuku.getText()+"', '"
                    +InputLokasiBuku.getText()+"')");
            JOptionPane.showMessageDialog(rootPane, "Data berhasil disimpan");
            InputKodeBuku.setText(null);
            InputJudulBuku.setText(null);
            InputPenerbit.setText(null);
            InputPenulis.setText(null);
            InputJumlahBuku.setText(null);
            InputLokasiBuku.setText(null);
            InputKodeBuku.requestFocus();
            tampil();
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(rootPane, "Database Error: " + error.getMessage());
            System.out.println("Database Error: " + error.getMessage());
        }
    }//GEN-LAST:event_ButtonSimpanActionPerformed

    private void ButtonTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTutupActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ButtonTutupActionPerformed

    private void ButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapusActionPerformed
        // TODO add your handling code here:
        InputKodeBuku.setEnabled(true);
        try {
            String kodeBuku = InputKodeBuku.getText();
            String query = "DELETE FROM tabel_buku WHERE kode_buku = '" + kodeBuku + "'";
            int result = connect.createStatement().executeUpdate(query);
            JOptionPane.showMessageDialog(rootPane, "Data '"+ kodeBuku + "' berhasil dihapus");
            System.out.println("Data '"+ kodeBuku + "' berhasil dihapus");
            tampil();
        }catch(SQLException error){
            JOptionPane.showMessageDialog(rootPane, "Database Error: " + error.getMessage());
            System.out.println("Database Error: " + error.getMessage());
        }
    }//GEN-LAST:event_ButtonHapusActionPerformed

    private void TabelBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelBukuMouseClicked
        // TODO add your handling code here:
        int selectedRow = TabelBuku.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) TabelBuku.getModel();

        // Ambil nilai dari tabel
        String kodeBuku = model.getValueAt(selectedRow, 0).toString();
        String judulBuku = model.getValueAt(selectedRow, 1).toString();
        String penerbit = model.getValueAt(selectedRow, 2).toString();
        String penulis = model.getValueAt(selectedRow, 3).toString();
        String jumlahBuku = model.getValueAt(selectedRow, 4).toString();
        String lokasiBuku = model.getValueAt(selectedRow, 5).toString();

        // Masukkan ke input field
        InputKodeBuku.setEnabled(false);
        InputKodeBuku.setText(kodeBuku);
        InputJudulBuku.setText(judulBuku);
        InputPenerbit.setText(penerbit);
        InputPenulis.setText(penulis);
        InputJumlahBuku.setText(jumlahBuku);
        InputLokasiBuku.setText(lokasiBuku);
    }//GEN-LAST:event_TabelBukuMouseClicked

    private void tampil(){
        try {
            table.setRowCount(0);
            ResultSet result = connect.createStatement().executeQuery("SELECT * FROM tabel_buku");
            while(result.next()){
                String[] data = {result.getString(1),result.getString(2),
                    result.getString(3),result.getString(4),result.getString(5),result.getString(6)};
                table.addRow(data);
            }
        }catch(SQLException error){
            System.out.println("Internal Server Error: " + error.getMessage());
            JOptionPane.showMessageDialog(rootPane, error);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormBuku dialog = new FormBuku(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBatal;
    private javax.swing.JButton ButtonCari;
    private javax.swing.JButton ButtonCetak;
    private javax.swing.JButton ButtonEdit;
    private javax.swing.JButton ButtonHapus;
    private javax.swing.JButton ButtonSimpan;
    private javax.swing.JButton ButtonTutup;
    private javax.swing.JTextField InputCari;
    private javax.swing.JTextField InputJudulBuku;
    private javax.swing.JTextField InputJumlahBuku;
    private javax.swing.JTextField InputKodeBuku;
    private javax.swing.JTextField InputLokasiBuku;
    private javax.swing.JTextField InputPenerbit;
    private javax.swing.JTextField InputPenulis;
    private javax.swing.JTable TabelBuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
